name: Deploy Azure Function

on:
  push:
    branches:
      - main # Adjust to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Adjust this to the Python version you're using

      - name: Set up Node.js (required for Azure Functions Core Tools)
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Adjust to the Node.js version you need

      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install distutils (required for Python)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt

      - name: Archive the Flask app
        run: |
          mkdir -p front-end-app
          cp -r main.py templates/ requirements.txt front-end-app/
          zip -r front-end-app.zip front-end-app

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mlopsassigment2fe'  # Replace with your Azure App Service name
          package: ./front-end-app.zip

      - name: Clean up
        run: |
          rm -rf front-end-app front-end-app.zip

      # - name: Publish to Azure Functions
      #   run: |
      #     func azure functionapp publish mlopsassigment2 --python
