name: Deploy Azure Function

on:
  push:
    branches:
      - main  # Adjust this to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust this to the Python version you're using

    - name: Set up Node.js (required for Azure Functions Core Tools)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can adjust to the Node.js version required

    - name: Install Azure Functions Core Tools
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Publish to Azure Functions
      run: |
        func azure functionapp publish <YOUR_FUNCTION_APP_NAME>
      env:
        AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
